services:
  nginx:
    image: nginx:latest
    container_name: nginx-docker-app-nginx
    volumes:
      - ./front:/var/www/front/
      - ./back/public:/var/www/html/public:ro
      - ./back/storage/app/public:/var/www/html/storage/app/public
      - ./.ci/nginx-default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "${APP_PORT:-80}:80"
    networks:
      - sail
    depends_on:
      - laravel.test
      - pgsql
      - react
  laravel.test:
    build:
      context: ./
      dockerfile: ./.ci/back.dockerfile
      args:
        WWWGROUP: '${WWWGROUP:-20}'
    image: nginx-docker-app-laravel
    container_name: nginx-docker-app-laravel
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      WWWUSER: '${WWWUSER}'
      LARAVEL_SAIL: 1
      XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
      XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
      IGNITION_LOCAL_SITES_PATH: '${PWD}'
    volumes:
      - './.env:/var/www/html/.env:ro'
      - './back:/var/www/html'
      - './.ci/php.ini:/usr/local/etc/php/conf.d/php.ini'
    networks:
      - sail
    depends_on:
      - pgsql
  pgsql:
    image: 'postgres:15'
    container_name: nginx-docker-app-db
    ports:
      - '${FORWARD_DB_PORT:-5432}:5432'
    environment:
      PGPASSWORD: '${DB_PASSWORD:-secret}'
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
    volumes:
      - 'sail-pgsql:/var/lib/postgresql/data'
      - './back/vendor/laravel/sail/database/pgsql/create-testing-database.sql:/docker-entrypoint-initdb.d/10-create-testing-database.sql'
    networks:
      - sail
    healthcheck:
      test:
        - CMD
        - pg_isready
        - '-q'
        - '-d'
        - '${DB_DATABASE}'
        - '-U'
        - '${DB_USERNAME}'
      retries: 3
      timeout: 5s
  react:
    build:
      context: ./
      dockerfile: ./.ci/front.dockerfile
    image: 'nginx-docker-app-react'
    container_name: nginx-docker-app-front
    ports:
      - '3000:3000'
    volumes:
      - './front:/var/www/front/'
      - './.env:/var/www/front/.env:ro'
    networks:
      - sail
networks:
  sail:
    name: nginx-docker-app-network
    driver: bridge
    external: true
volumes:
  sail-pgsql:
    driver: local
  sail-react:
    driver: local
